### ISSUE TITLE
Remove `zone_letter` and `northern`

### ISSUE THREAD

**Issue by greatvovan** [Turbo87/utm#108]
Latitude bands are not part of UTM specification. Similarly, northing ranges for North and South hemispheres do not overlap. Therefore, `zone_letter` and `northern` parameters seem redundant and not needed for conversion.

It is okay however to output them when converting **to** UTM. But I think they should be removed from `to_latlon()` function.

https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system

**Comment by bartvanandel** [comment]
While you are technically correct, "They are however sometimes included in UTM notation" as the Wikipedia article also notes. Why would it be okay to output them, but not to accept them as input? Removing zone letter support from `to_latlon()` complicates converting these values unnecessarily.

Won't fix.
