### ISSUE TITLE
Inaccurate and asymmetric (North/South) transformation utm to lat lon

### ISSUE THREAD

**Issue by camillechasset** [Turbo87/utm#120]
There is apparently an error (wrong parenthesis position) in the transformation from UTM to lat / lon, at this line: https://github.com/Turbo87/utm/blob/418d9c477003b1aa18be551f4c46ff689c9c2dc2/utm/conversion.py#L172

Original computation:
```
    latitude = (p_rad - (p_tan / r) *
                (d2 / 2 -
                 d4 / 24 * (5 + 3 * p_tan2 + 10 * c - 4 * c2 - 9 * E_P2)) +
                 d6 / 720 * (61 + 90 * p_tan2 + 298 * c + 45 * p_tan4 - 252 * E_P2 - 3 * c2))
```
Proposed change:
```
    latitude = p_rad - (p_tan / r) *
                (d2 / 2 -
                 d4 / 24 * (5 + 3 * p_tan2 + 10 * c - 4 * c2 - 9 * E_P2) +
                 d6 / 720 * (61 + 90 * p_tan2 + 298 * c + 45 * p_tan4 - 252 * E_P2 - 3 * c2))
```
One simple thing to notice is that the original correction term in `d6` had the same sign in the North and South hemisphere whereas it is expected to change.
I attach some plots showing the performance improvement when implementing this change, evaluated by doing the double conversion from utm to lat/lon and then back:

- Residual errors excluding Norway exceptions, before fix (left) and after (right), error reduced from up to 4.5mm to 0.8mm (decreased by a factor ~6). Note the North / South asymmetry.
![latlonErrorNoExceptions](https://github.com/Turbo87/utm/assets/52002097/47852620-b290-43a0-84df-04ad893be47a)
- Same, including Norway exception. Error reduced from up to 6.5cm to 6.5mm (decreased by a factor ~10).
![latlonErrorNorway](https://github.com/Turbo87/utm/assets/52002097/9885e4b2-7e83-4159-a9f5-9076fa595b6a)
- Same, including Svalbard exception. Error reduced from up to 8cm to 13mm (decreased by a factor ~6).
![latlonErrrorSvalbard](https://github.com/Turbo87/utm/assets/52002097/524494ea-cf2c-45ba-8ff2-8befadffb5a4)

I didn't manage to find the source of the code, but on [this page](https://en.wikipedia.org/wiki/Transverse_Mercator:_Redfearn_series#Inverse_series) you can see a similar series decomposition, and all terms of the latitude expression series are multiplied by `beta1*t1`, which in your code is `(p_tan / r)`. That's why I believe the change is needed.

**Comment by camillechasset** [comment]
> There is apparently an error (wrong parenthesis position) in the transformation from UTM to lat / lon, at this line:
> 
> https://github.com/Turbo87/utm/blob/418d9c477003b1aa18be551f4c46ff689c9c2dc2/utm/conversion.py#L172
> 
> Original computation:
> 
> ```
>     latitude = (p_rad - (p_tan / r) *
>                 (d2 / 2 -
>                  d4 / 24 * (5 + 3 * p_tan2 + 10 * c - 4 * c2 - 9 * E_P2)) +
>                  d6 / 720 * (61 + 90 * p_tan2 + 298 * c + 45 * p_tan4 - 252 * E_P2 - 3 * c2))
> ```
> 
> Proposed change:
> 
> ```
>     latitude = p_rad - (p_tan / r) *
>                 (d2 / 2 -
>                  d4 / 24 * (5 + 3 * p_tan2 + 10 * c - 4 * c2 - 9 * E_P2) +
>                  d6 / 720 * (61 + 90 * p_tan2 + 298 * c + 45 * p_tan4 - 252 * E_P2 - 3 * c2))
> ```
> 
> One simple thing to notice is that the original correction term in `d6` had the same sign in the North and South hemisphere whereas it is expected to change. I attach some plots showing the performance improvement when implementing this change, evaluated by doing the double conversion from utm to lat/lon and then back:
> 
> * Residual errors excluding Norway exceptions, before fix (left) and after (right), error reduced from up to 4.5mm to 0.8mm (decreased by a factor ~6). Note the North / South asymmetry.
>   ![latlonErrorNoExceptions](https://private-user-images.githubusercontent.com/52002097/313769853-47852620-b290-43a0-84df-04ad893be47a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTI1NTUsIm5iZiI6MTcxMzQ1MjI1NSwicGF0aCI6Ii81MjAwMjA5Ny8zMTM3Njk4NTMtNDc4NTI2MjAtYjI5MC00M2EwLTg0ZGYtMDRhZDg5M2JlNDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE0NTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwOGE4NDQyNjRkNGE4MGJiZDI0ZmFhOTkxMWNmMDRiNDEzM2I2ZjU3MDVlYjcwNDc3ZjZjM2IzMzZiNzZlMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8-gZKLEmE1atm9HpBS81M6lBtTTuV5K9_aupNJfGKP8)
> * Same, including Norway exception. Error reduced from up to 6.5cm to 6.5mm (decreased by a factor ~10).
>   ![latlonErrorNorway](https://private-user-images.githubusercontent.com/52002097/313769849-9885e4b2-7e83-4159-a9f5-9076fa595b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTI1NTUsIm5iZiI6MTcxMzQ1MjI1NSwicGF0aCI6Ii81MjAwMjA5Ny8zMTM3Njk4NDktOTg4NWU0YjItN2U4My00MTU5LWE5ZjUtOTA3NmZhNTk1YjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE0NTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjN2M0MWJkNjE0NGZjNDI2NzljY2Y3N2ZhNTMwMzg5MmVkNjVkODNlYTZjYWExMmU5Yzg3OTA1NTcwM2ZjZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cFCiOE-iulN8pz4rrT7B57U18uv-k_z9ld-vpjun91Y)
> * Same, including Svalbard exception. Error reduced from up to 8cm to 13mm (decreased by a factor ~6).
>   ![latlonErrrorSvalbard](https://private-user-images.githubusercontent.com/52002097/313769842-524494ea-cf2c-45ba-8ff2-8befadffb5a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTI1NTUsIm5iZiI6MTcxMzQ1MjI1NSwicGF0aCI6Ii81MjAwMjA5Ny8zMTM3Njk4NDItNTI0NDk0ZWEtY2YyYy00NWJhLThmZjItOGJlZmFkZmZiNWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE0NTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZGE5MjEyZTkxNzY1NjUzYjNhNTgyYjJjODM5MDAzMmI3NWNlMDk1MDA5MGM0YjVjYWE0M2UyZDMzMmU3M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RPG07YBc0I_3lR5_kw33qARj7z2_Ei-3VWoZ8F3gk94)
> 
> I didn't manage to find the source of the code, but on [this page](https://en.wikipedia.org/wiki/Transverse_Mercator:_Redfearn_series#Inverse_series) you can see a similar series decomposition, and all terms of the latitude expression series are multiplied by `beta1*t1`, which in your code is `(p_tan / r)`. That's why I believe the change is needed.

@Turbo87 any thoughts about this? :pray:

**Comment by tvkn** [comment]
Hey @Turbo87! Can we help by opening a PR to fix this?
Thanks!

**Comment by bartvanandel** [comment]
Very good catch. I included your proposed fix, thanks a bunch! <3
