### ISSUE TITLE
Zone number ignored near equator

### ISSUE THREAD

**Issue by jeremy-faller** [Turbo87/utm#17]
Tried the following:

``` python
>>> utm.conversion.from_latlon(0.001,0.001)
(166132.8718804731, 110.68265407867526, 31, 'N')
>>> utm.conversion.from_latlon(-0.001,-0.001)
(833867.1281195269, 9999889.317345921, 30, 'M')
>>> utm.conversion.from_latlon(-0.001,-0.001,31)
(165910.01447681867, 9999889.317142073, 31, 'M')
```

You'll note the zone number is ignored. I believe this is a generic problem in that we can't pass the zone_letter to the from_latlon function.

**Comment by Turbo87** [comment]
sorry, I don't understand the problem here. in the third call you force the zone number to be `31` and the result shows `31`. what is wrong with that?

**Comment by Turbo87** [comment]
maybe @tibnor can help here since he wrote that part of the code in #8

**Comment by jeremy-faller** [comment]
You're right -- not clear. My bad on the bug report.

Better is:


```python
>>> utm.conversion.from_latlon(-0.001,-0.001,30)
(833867.1281195269, 9999889.317345921, 30, 'M')
```

**Comment by tarnhold** [comment]
Zone numbers increase from west to east.

With 10.000.000 you mean the Northing, which is correct.

# north of equator
>>> utm.conversion.from_latlon(0.001, 0)
(166021.44322995137, 110.68275598603395, 31, 'N')

# south of equator
>>> utm.conversion.from_latlon(-0.001, 0)
(166021.44322995137, 9999889.317244014, 31, 'M')

# south of equator, force zone 31
>>> utm.conversion.from_latlon(-0.001, 0, 31)
(166021.44322995137, 9999889.317244014, 31, 'M')

# south of equator, force zone 30 - you see that only Easting changed
>>> utm.conversion.from_latlon(-0.001, 0, 30)
(833978.5567700486, 9999889.317244014, 30, 'M')

**Comment by bartvanandel** [comment]
If you force the zone to 31 and the letter to 'N', you'll get the value you expect. The negative value is officially "out of zone":

```py
utm.conversion.from_latlon(-0.001,-0.001, 31, 'N')
(165910.01447681856, -110.68285792752474, 31, 'N')
```

Alternatively, you can now use `force_northern=True` to achieve the same result. Note that you will not get a zone letter in return if you do this:

```py
utm.conversion.from_latlon(-0.001,-0.001, 31, force_northern=True)
(165910.01447681856, -110.68285792752474, 31, None)
```
