### ISSUE TITLE
UTM zone exceptions error

### ISSUE THREAD

**Issue by hogend** [Turbo87/utm#19]
By definition zones are left-closed, right-open intervals, e.g. zone 31: 0 <= latitude < 6.
In function latlon_to_zone_number:

```
if 72 <= latitude <= 84 and longitude >= 0:
    if longitude <= 9:
        return 31
    elif longitude <= 21:
        return 33
    elif longitude <= 33:
        return 35
    elif longitude <= 42:
        return 37
```

For latitudes >=72, this results in:
zone 31: 0  <= longitude <= 9
zone 33: 9  <   longitude <= 21
zone 35: 21<   longitude <= 33
zone 37: 33<   longitude <= 42

but for latitudes < 72:
zone 37: 36 <= latitude < 42

**Comment by Turbo87** [comment]
@hogend thanks for reporting this! do you think you could open a pull request with the suggested changes?

**Comment by Juanlu001** [comment]
I'm interested in looking into this too, but I could not find any source or reference that supports the first statement: "By definition zones are left-closed, right-open intervals". Any material on this?

**Comment by hogend** [comment]
On Fri, Jun 23, 2017 at 03:45:19AM -0700, Juan Luis Cano Rodríguez wrote:
> I'm interested in looking into this too, but I could not find any source or reference that supports the first statement: "By definition zones are left-closed, right-open intervals". Any material on this?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/Turbo87/utm/issues/19#issuecomment-310634487

Hello,

I am sorry for the late reply, but I have been sailing the last couple weeks with very limited internet connectivity.
The definite reference for UTM is Technical Manual 8358.1 (see http://earth-info.nga.mil/GandG/publications/ ).
A more elaborate explanation is given in NGA.SIG.0012_2.0.0_UTMUPS (Version 2.0.0 - March 25, 2014): The Universal Grids and the Transverse Mercator and Polar Stereographic Map Projectionsm; especially in section 7.4 (document 4. at the above mentioned website).
Hope this helps,
Regards,

Rene Hogendoorn

**Comment by Juanlu001** [comment]
Awesome @hogend, that is *exactly* what I meant. In section 7.5 of NGA.SIG.0012_2.0.0_UTMUPS we have the full pseudocode:

![screenshot-2017-7-4 the-universal-grids_v7e_plain nb - nga sig 0012_2 0 0_utmups pdf](https://user-images.githubusercontent.com/316517/27829986-9ca2cd4e-60c4-11e7-88fc-f5f843383328.png)
