### ISSUE TITLE
Add version information to the Python module

### ISSUE THREAD

**Issue by mairsbw** [Turbo87/utm#21]
It's helpful when checking dependencies programmatically or for a developer to be able to retrieve version information from the modules `__version__` attribute (see [PEP396](https://www.python.org/dev/peps/pep-0396/)).

Our use case is a `check_dependencies.py` script that the developer can run to verify they have all necessary packages installed and that they're the correct version.

**Comment by Turbo87** [comment]
@mairsbw can you open a pull request for that with the necessary changes?

**Comment by mairsbw** [comment]
Unfortunately I cannot right now. This is a nice-to-have for work, but I'm not able to allocate time for this for the next few weeks.

**Comment by Turbo87** [comment]
closing this for now. feel free to open a PR once you find time for it and thanks for the suggestion
