### ISSUE TITLE
License for Conda

### ISSUE THREAD

**Issue by snowman2** [Turbo87/utm#28]
Hello,

I have found your code to be very useful. I see a license in your readme. However, it would be nice for you to generate a separate license file with an official license type (BSD, Apache, MIT, ...) and include it in your MANIFEST.in. The reason is that it would be nice to turn this into a conda package (see: https://github.com/conda-forge/staged-recipes) and they require a license to be included.

Thanks!

**Comment by Turbo87** [comment]
@snowman2 as you may have noticed I'm using the MIT license here. feel free to open a pull request with the necessary changes to make this compatible.

**Comment by snowman2** [comment]
Thanks for merging. When will the version with the license be released to pypi?

**Comment by Turbo87** [comment]
should be up in a few minutes once https://travis-ci.org/Turbo87/utm/builds/219342206 is complete

closing as this was resolved by #29 

thanks!

**Comment by Turbo87** [comment]
https://pypi.python.org/pypi/utm/0.4.2

**Comment by snowman2** [comment]
Thanks!

Would you like to be a package maintainer on conda-forge as well? It's not too bad to get the hang of.

**Comment by Turbo87** [comment]
@snowman2 since I'm not using that myself I don't think that would make sense, but thanks for asking

**Comment by snowman2** [comment]
@Turbo87 would you like me to remove you from the co-maintainer list?
