### ISSUE TITLE
conversion to lat long totally innacurate

### ISSUE THREAD

**Issue by BenCrittenden** [Turbo87/utm#37]
I'm trying to convert some easting / northing points in Northallerton, Yorkshire, UK into long lat coordinates. The output is totally wrong:

In: utm.to_latlon(436721, 494027, 30, 'U')
Out: (4.469304260779383, -3.570385960423369)

The correct lat lon is:
54.34048167227063 -1.4366966408566932

I believe that the 30U grid is the appropriate one for this region (I have tried other grid references, which also produce an inaccurate result).

(using pyproj as below does give the correct lat/lon coordinates:
bng = pyproj.Proj(init='epsg:27700')
wgs84 = pyproj.Proj(init='epsg:4326')
pyproj.transform(bng,wgs84, 436721, 494027)
(54.34048167227063 -1.4366966408566932)

I will just use the pyproj library for my purposes as speed isn't crucial, but thought I would report the issue.

**Comment by Turbo87** [comment]
```py
>>> import utm
>>> utm.from_latlon(54.34048167227063, -1.4366966408566932)
(601631.7612208668, 6022531.538950634, 30, 'U')
>>> utm.to_latlon(601631.7612208668, 6022531.538950634, 30, 'U')
(54.34048167371927, -1.4366965273224754)
```

I don't know how you got those UTM coordinates, but they don't seem to match your WGS84 coordinate. Feel free to check with an independent tool like https://www.latlong.net/lat-long-utm.html
