### ISSUE TITLE
Why are there two 'X' value in ZONE_LETTERS?

### ISSUE THREAD

**Issue by apiszcz** [Turbo87/utm#38]
I'm guessing this my understanding and intentional, thank you for the module.

ZONE_LETTERS = "CDEFGHJKLMNPQRSTUVWXX"

**Comment by Turbo87** [comment]
because the "X" zone is larger than the others. see https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Latitude_bands_2
