### ISSUE TITLE
no attribute 'from_latlon'

### ISSUE THREAD

**Issue by fatgenius** [Turbo87/utm#43]
```
File "utm.py", line 4, in <module>
    import utm
  File "/home/tea/Desktop/utm.py", line 9, in <module>
    u = utm.from_latlon(30.44085275, 103.58441172)
AttributeError: 'module' object has 
```

**Comment by Turbo87** [comment]
sorry, I don't know what this means. the error is incomplete and with incomplete information we can't attempt to fix this.

**Comment by JackMiranda** [comment]
Try 
```
from utm.conversion import from_latlon
```
instead.

**Comment by fatgenius** [comment]
> sorry, I don't know what this means. the error is incomplete and with incomplete information we can't attempt to fix this.

thanks so much. already solved problem. but new  question coming up.Could you help me? thanks in advance.
 utm.from_latlon(3044.2543894,10358.3156079)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/utm/conversion.py", line 190, in from_latlon
    raise OutOfRangeError('latitude out of range (must be between 80 deg S and 84 deg N)')
utm.error.OutOfRangeError: latitude out of range (must be between 80 deg S and 84 deg N)

I`m current testing the code in china, any location problems?  Thanks again

**Comment by Turbo87** [comment]
`3044.2543894` is not a valid latitude values as the error mentions, they must be between 84 and -80 and 3044 is outside of that range.

**Comment by fatgenius** [comment]
> `3044.2543894` is not a valid latitude values as the error mentions, they must be between 84 and -80 and 3044 is outside of that range.

Thanks again,
The data type I been using is GNGLL.  Any way could convert it to the require data type?
Dank.

**Comment by Turbo87** [comment]
> The data type I been using is GNGLL.

I've never heard of GNGLL, sorry.
