### ISSUE TITLE
How to obtain the utm zone value corresponding to a specific city, say, Beijing?

### ISSUE THREAD

**Issue by hongyi-zhao** [Turbo87/utm#64]
Hi,

I want to use utm package to obtain the utm zone value corresponding to a specific city, say, Beijing. I've read some discussions [here](https://gis.stackexchange.com/questions/269518/auto-select-suitable-utm-zone-based-on-grid-intersection) but still not so clear on the concrete steps. Any hints will be highly appreciated.

Regards,
HY

**Comment by Turbo87** [comment]
you need to find the latitude and longitude values of the city and then pass them into the `from_latlon()` function
