### ISSUE TITLE
Feature Request: Add MTM<->UTM conversion

### ISSUE THREAD

**Issue by pbouill** [Turbo87/utm#67]
Hello,

Wondering if it would be simple to add mtm<->utm coordinate system conversions? There are some online tools for converting from mtm<->lat/lon and utm<->lat/lon (e.g. http://leware.net/geo/utmgoogle.htm, script embedded in the htm code). Would be awesome if this package handled mtm...

**Comment by bartvanandel** [comment]
It seems that MTM, or Modified Transverse Mercator, is quite niche. Its [Wikipedia page](https://en.wikipedia.org/wiki/Modified_transverse_Mercator "Modified transverse Mercator") is only 3 sentences long, one of which says:

> The coordinate system is used in [Eastern Canada](https://en.wikipedia.org/wiki/Eastern_Canada).

... and it still needs a citation for that statement.

Another source, [Manifold.net](https://manifold.net/doc/mfd8/modified_transverse_mercator.htm "Modified Transverse Mercator") states (emphasis mine):

> A USGS projection developed in 1972 for the revision of a 1954 map of Alaska. Consisting of an adaptation for the [Universal Transverse Mercator](https://manifold.net/doc/mfd8/universal_transverse_mercator_utm_.htm) projection series, it is not really a cylindrical projection but is better understood as an approximation to the [Equidistant Conic](https://manifold.net/doc/mfd8/equidistant_conic.htm) projection. This projection is **used for maps of Alaska and the Aleutian - Bering Sea region** and is **best left for experts only**.

Even EPSG.io notes that the transform accuracy is only about 2 meters at best with supported coordinate systems, see e.g. [EPSG:32181: NAD83 / MTM zone 1](https://epsg.io/32181)

I'm gonna go ahead and say this doesn't really fit the purpose of the universally applicable `utm` library.
