### ISSUE TITLE
The unit of easting and northing

### ISSUE THREAD

**Issue by deHsien** [Turbo87/utm#71]
The unit of easting and northing seems not to be meter. Is there any bug or it is in another unit ?

**Comment by bartvanandel** [comment]
I'm not sure what you mean. The units of UTM are meters. Quoting from [Wikipedia](https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system "Universal Transverse Mercator coordinate system"):

> In the northern hemisphere positions are measured northward from zero at the equator. The maximum "northing" value is about 9300000 meters at latitude 84 degrees North, the north end of the UTM zones. The southern hemisphere's northing at the equator is set at 10000000 meters. Northings decrease southward from these 10000000 meters to about 1100000 meters at 80 degrees South, the south end of the UTM zones. Therefore, no point has a negative northing value.

If you have an issue with that, I'm afraid you'll have to take it up with the standards body which defined the UTM coordinate system 😉
