### ISSUE TITLE
Returning wrong zone!

### ISSUE THREAD

**Issue by jtamerius** [Turbo87/utm#78]
I am using utm version 0.4.2 and I have tried version 0.7.0 from conda-forge and from pip. I keep getting the wrong zone for the following:

utm.from_latlon(32.7,-117)
(500000.0, 3618029.7144259233, 11, 'S')

I see from a previous issue ([#63](https://github.com/Turbo87/utm/issues/63)) there are some versions that provide incorrect zones? Which version should I use?

**Comment by randallpittman** [comment]
Multiple online converters give the same result. Why do you think this is wrong?

**Comment by bartvanandel** [comment]
@jtamerius Is this still an issue for you?

**Comment by jtamerius** [comment]
> @jtamerius Is this still an issue for you?

I have no memory of this issue. So, I guess not.

**Comment by bartvanandel** [comment]
In that case, would you mind closing it? :)

**Comment by jtamerius** [comment]
Never!!! 🏴‍☠️
