### ISSUE TITLE
Convertion of Gauss-Krueger coordinates

### ISSUE THREAD

**Issue by jnphilipp** [Turbo87/utm#79]
I'm trying to change the calculation, so that I can convert Gauss-Krueger coordinates. As far as I understand the [difference](https://coordinates-converter.com/en/info) is only that they use a different ellipsoide, i.e. [Bessel](https://en.wikipedia.org/wiki/Bessel_ellipsoid) in stead of WGS84, and the zones are 3° wide instead of 6°.

So I changed:
```python
E = 0.006674372230688468
R = 6377397.155

def latlon_to_zone_number(latitude, longitude):
    ...
    return int((longitude + 180) / 3) + 1

def zone_number_to_central_longitude(zone_number):
    return (zone_number - 1) * 3 - 180 + 1.5
```

But my coorfiantes are way off:
```
from_latlon(50, 10)
464170.9085434285 5538183.190657409
# excpected
3571770.862 5540886.852
```

What am I missing?

**Comment by bartvanandel** [comment]
I'm by no means an expert here, but from reading the [Wikipedia](https://en.wikipedia.org/wiki/Transverse_Mercator_projection#Ellipsoidal_transverse_Mercator) article, Gauss-Krüger actually applies to ellipsoidal transverse Mercator, which is quite a different shape from the cylindrical shape used by UTM.

Apparently though, the term "Gauss-Krüger" is sometimes also used for slightly different things, one of which being a way to convert to/from lat/lon, but this is only usable relatively near the equator. Wikipedia says:

> Sometimes, the term is used for a particular computational method for transverse Mercator: that is, how to convert between latitude/longitude and projected coordinates. There is no simple closed formula to do so when the earth is modelled as an ellipsoid. But the Gauss–Krüger method gives the same results as other methods, at least if you are sufficiently near the central meridian: less than 100 degrees of longitude, say. Further away, some methods become inaccurate.

So, correct me if I'm wrong, but it's not just a different ellipsoid, but a whole different set of formulae, not compatible with the ones used by `utm` here. Enough reason to close this issue, I think.

I'm closing this one for now. Of course, feel free to prove me wrong and open a PR.
