### ISSUE TITLE
wrong Easting when trying to convert hurricane katrina track from lon lat to utm

### ISSUE THREAD

**Issue by albacidcarrera** [Turbo87/utm#83]
I'm attaching a picture that summarizes my problem. In blue and orange you can see the correct US coast and hurricane track, in black is what I obtain using utm.from_latlon. Coast appears to be moved to east while track is moved west.

Do you know what might be happening?
Thanks

![download (2)](https://user-images.githubusercontent.com/35835809/166437903-845a3348-41ed-46ea-860f-a2361f4c3b6b.png)

**Comment by jjccmm** [comment]
I can imagine that you transformed your coordinates into different UTM Zones. Check the zone of the correct (blue/yellow) coordinates and compare what you get with utm.from_latlon. 
To convert all coordinates into a particular zone use the batch conversation with numpy arrays and add a coordinate from the desired zone to the beginning of the arrays.

**Comment by bartvanandel** [comment]
Closing as stale. Also, not enough information provided to actually try and reproduce the issue.
