### ISSUE TITLE
Unexpected behavior when using np.arrays

### ISSUE THREAD

**Issue by SimoneRaponi** [Turbo87/utm#92]
I am using conda-forge's utm v. 0.7.0.

It seems that utm.from_latlon function, when given as input a np.array, considers all the coordinates within the same zone as the first coordinate.

To clarify, 

array(
  [[55.        , 30.        ],
  [x.        , y.        ],
  [w.        , z.        ])

provides for [55, 30], [x,y], and [w,z] UTM coordinates as if all of them were within the [55, 30] zone, even if they actually do not.

**Comment by bartvanandel** [comment]
This is currently intended behavior, I assume for performance reasons, see also #94. But I agree it's counter-intuitive.
